// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbp3IR0wQC0IPojkenN4dv511-BAGapq4',
    appId: '1:512008866114:web:8dc15a1d2f1ececc0620db',
    messagingSenderId: '512008866114',
    projectId: 'groupchat-6869d',
    authDomain: 'groupchat-6869d.firebaseapp.com',
    storageBucket: 'groupchat-6869d.appspot.com',
    measurementId: 'G-X986ZW4YS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMa3PH-dGWpnhwIfh0c28zhh7EZPXghsA',
    appId: '1:512008866114:android:db79e9965c610d770620db',
    messagingSenderId: '512008866114',
    projectId: 'groupchat-6869d',
    storageBucket: 'groupchat-6869d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgcwezFjdkkVZqeeM6_3dshb4D7p1urUM',
    appId: '1:512008866114:ios:544db72036d5b77f0620db',
    messagingSenderId: '512008866114',
    projectId: 'groupchat-6869d',
    storageBucket: 'groupchat-6869d.appspot.com',
    iosClientId: '512008866114-qaee8hcdr36c2qf2cghfp5a404gjsj2o.apps.googleusercontent.com',
    iosBundleId: 'com.example.groupChatFb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgcwezFjdkkVZqeeM6_3dshb4D7p1urUM',
    appId: '1:512008866114:ios:544db72036d5b77f0620db',
    messagingSenderId: '512008866114',
    projectId: 'groupchat-6869d',
    storageBucket: 'groupchat-6869d.appspot.com',
    iosClientId: '512008866114-qaee8hcdr36c2qf2cghfp5a404gjsj2o.apps.googleusercontent.com',
    iosBundleId: 'com.example.groupChatFb',
  );
}
